### ISSUE TITLE
Error dragging anything to character sheet

### ISSUE THREAD

**Issue by lordwey** [fh-fvtt/zweihander#205] opened 2023-09-23 14:23 UTC
![image](https://github.com/fh-fvtt/zweihander/assets/34535551/3979fbb0-442b-46b2-bd99-093a32705889)

**Comment by lordwey** [comment] 2023-09-23 14:23
![image](https://github.com/fh-fvtt/zweihander/assets/34535551/d3b91cbb-3350-4758-ad7f-8b4c9e31ebc6)

**Comment by Re4XN** [comment] 2023-09-23 16:45
Without any further description (examples of which are thoroughly detailed in the [bug report submission form](https://github.com/fh-fvtt/zweihander/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=), there's nothing to go off of for us to fix this.

Tested on the latest version of FoundryVTT (11.309), in a new world with no modules and cannot reproduce. Closing.

**Closed by Re4XN** 2023-09-23 16:45 UTC
